[package]
name = "meta_nestris"
version = "0.2.0"
edition = "2021"

[dependencies]
bitmask-enum = "=2.1.0"
bitvec = "=1.0.1"
regex = "=1.7.0"
static_init = "=1.0.3"

[dev-dependencies]
serde = { version = "=1.0.148", features = ["derive"] }
serde_yaml = "=0.9.14"
